spring:
  application:
    name: ms-customers
  config:
    # LOCAL
    import: optional:configserver:http://ms-config-service:9001
    # AZURE
    # import: optional:configserver:http://ms-config-service.azurewebsites.net
